document.write( '<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\n' );
document.write( '        <nav class=\"navbar navbar-default navbar-static-top\">\n' );
document.write( '            <div class=\"container-fluid\">\n' );
document.write( '                <a class=\"navbar-brand\" href=\"index.html\" class=\"logo\">.Maddie K.</a>\n' );
document.write( '                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\" aria-controls=\"offcanvasNavbar\" aria-label=\"Toggle navigation\">\n' );
document.write( '                    <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '                </button>\n' );
document.write( '                <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\">\n' );
document.write( '                    <div class=\"offcanvas-header justify-content-end\">\n' );
document.write( '                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"offcanvas-body\">\n' );
document.write( '                        <ul class=\"nav-links navbar-nav\">\n' );
document.write( '                            <li class=\"link nav-item\"><a href=\"index.html\">HOME</a></li>\n' );
document.write( '                            <li class=\"link nav-item\"><a href=\"about.html\">ABOUT</a></li>\n' );
document.write( '                            <li class=\"link nav-item\"><a href=\"resume.html\">RESUME</a></li>\n' );
document.write( '                            <li class=\"link nav-item\"><a href=\"projects.html\">PROJECTS</a></li>\n' );
document.write( '                            <li class=\"link nav-item dropdown\">\n' );
document.write( '                                <a class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" href=\"#\">CONTACT</a>\n' );
document.write( '                                <ul class=\"dropdown-menu\">\n' );
document.write( '                                    <li><a class=\"dropdown-item\" href=\"mailto:ykong@oswego.edu\"><i class=\"fa-regular fa-envelope\" style=\"color: #87cbff;\"></i>  ykong@oswego.edu</a></li>\n' );
document.write( '                                    <li><a class=\"dropdown-item\" href=\"https://github.com/maddie-y-k\"><i class=\"fa-brands fa-square-github\" style=\"color: #87cbff;\"></i>    maddie-y-k</a></li>\n' );
document.write( '                                </ul>\n' );
document.write( '                            </li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </nav>' );


